//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalHistory()
        {
            this.TreatmentSheet = new HashSet<TreatmentSheet>();
        }
    
        public int ID { get; set; }
        public int IdPatient { get; set; }
        public int IdDoctor { get; set; }
        public string Diagnosis { get; set; }
        public string DateDisease { get; set; }
        public string DateCure { get; set; }
        public string TypeTreatment { get; set; }
        public string Image { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentSheet> TreatmentSheet { get; set; }
    }
}
